# Generated by Django 3.1.6 on 2022-07-19 08:30

import Room.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in', models.DateField(verbose_name='Дата заезда')),
                ('day_out', models.DateField(verbose_name='Дата выезда')),
                ('number_of_guests', models.IntegerField(null=True, verbose_name='Количество гостей')),
                ('reg_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации резерва')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Резерв комнаты',
                'verbose_name_plural': 'Резервы комнат',
            },
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('nomination', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип комнаты',
                'verbose_name_plural': 'Типы комнат',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('price', models.IntegerField(help_text='указывать в рублях', null=True, verbose_name='Цена')),
                ('number_of_guests', models.IntegerField(null=True, verbose_name='Количество гостей')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.hotel', verbose_name='Отель')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Room.typeroom', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('reserve', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.reserve', verbose_name='Резерв ID')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Отзыв комнаты',
                'verbose_name_plural': 'Отзывы комнат',
            },
        ),
        migrations.AddField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.room', verbose_name='Комната'),
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.TextField(blank=True, null=True, verbose_name='Правило')),
                ('type_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Room.typeroom', verbose_name='Тип комнаты')),
            ],
            options={
                'verbose_name': 'Правило комнаты',
                'verbose_name_plural': 'Правила комнат',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_photo1', models.ImageField(blank=True, help_text='Фотография будет отображаться в слайдере', null=True, upload_to=Room.models.catalog_of_photo_rooms, verbose_name='Фото 1')),
                ('slider_photo2', models.ImageField(blank=True, help_text='Фотография будет отображаться в слайдере', null=True, upload_to=Room.models.catalog_of_photo_rooms, verbose_name='Фото 2')),
                ('slider_photo3', models.ImageField(blank=True, help_text='Фотография будет отображаться в слайдере', null=True, upload_to=Room.models.catalog_of_photo_rooms, verbose_name='Фото 3')),
                ('slider_photo4', models.ImageField(blank=True, help_text='Фотография будет отображаться в слайдере', null=True, upload_to=Room.models.catalog_of_photo_rooms, verbose_name='Фото 4')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos_of_room', to='Room.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Галерея комнаты',
                'verbose_name_plural': 'Галереи комнат',
            },
        ),
    ]
